import * as React from "react";

import { Button } from "@/components/base/button";
import { Paper } from "@/components/base/paper";
import { TextInput } from "@/components/base/text-input";
import { Grid } from "@/components/base/grid";
import { Checkbox } from "@/components/base/checkbox";
import { Alert } from "@/components/base/alert";

import { Dashboard } from "@/components/layouts/dashboard";
import { Actionbar } from "@/components/layouts/action-bar";

import { ArrowLeftIcon } from "@/components/icons/arrow-left-icon";
import { CheckIcon } from "@/components/icons/check-icon";
import { SpinnerIcon } from "@/components/icons/spinner-icon";

import { useTimeout } from "@/hooks/use-timeout";
import { useForm } from "@/hooks/use-form";

import { makeCreateQRConfigurationMasterService } from "@/services/create-qr-configuration-master-service";

type CreateQRConfigurationMasterProps = {
  sessionId: string;
  onBack: () => void;
};

const delayAfterSuccess = 1000;

export const CreateQRConfigurationMaster = ({
  sessionId,
  onBack,
}: CreateQRConfigurationMasterProps): JSX.Element => {
  // QR Config ID is auto-generated by backend/system
  const [qrConfigId, setQrConfigId] = React.useState<string>("AUTO-GENERATED");
  const [expiryHours, setExpiryHours] = React.useState<string>("");
  const [isOneTimeScan, setIsOneTimeScan] = React.useState<boolean>(false);
  const [isGateValidation, setIsGateValidation] = React.useState<boolean>(false);
  const [isPdfRequired, setIsPdfRequired] = React.useState<boolean>(false);
  const [isActive, setIsActive] = React.useState<boolean>(true);

  const [isSuccess, setIsSuccess] = React.useState<boolean>(false);

  const { startTimeout } = useTimeout();

  const handleSuccess = React.useCallback(() => {
    setIsSuccess(true);
    startTimeout(() => {
      onBack();
    }, delayAfterSuccess);
  }, [startTimeout, onBack]);

  const { isLoading, alertData, validation, submit } = useForm({
    serviceMaker: makeCreateQRConfigurationMasterService,
    onSuccess: handleSuccess,
  });

  const handleSubmit = React.useCallback(() => {
    submit({
      sessionId,
      expiryHours: Number(expiryHours),
      isOneTimeScan,
      isGateValidation,
      isPdfRequired,
      isActive,
    });
  }, [
    sessionId,
    expiryHours,
    isOneTimeScan,
    isGateValidation,
    isPdfRequired,
    isActive,
    submit,
  ]);

  return (
    <Dashboard.Content>
      <Actionbar title="CREATE QR CONFIGURATION MASTER">
        <Button
          label="SAVE"
          icon={isLoading ? <SpinnerIcon /> : <CheckIcon />}
          isDisabled={
            isLoading ||
            !expiryHours ||
            isNaN(Number(expiryHours)) ||
            isSuccess
          }
          onClick={handleSubmit}
        />
        <Button label="GO BACK" icon={<ArrowLeftIcon />} onClick={onBack} />
      </Actionbar>

      <Dashboard.Page>
        <Paper>
          {alertData !== null && (
            <Alert message={alertData.message} severity={alertData.severity} />
          )}

          <Paper.Title value="QR Configuration Details" />

          <Grid>
            {/* Field 1: QR Config ID (Auto Generated - Read Only) */}
            <Grid.Cell size={Grid.CellSize.S3}>
              <TextInput
                className="w-100"
                label="QR Config ID"
                value={qrConfigId}
                isDisabled={true}
              />
            </Grid.Cell>

            {/* Field 2: Expiry Hours */}
            <Grid.Cell size={Grid.CellSize.S3}>
              <TextInput
                className="w-100"
                label="Expiry Hours"
                placeholder="Enter expiry in hours"
                value={expiryHours}
                hasError={typeof validation["expiryHours"] !== "undefined"}
                isDisabled={isLoading || isSuccess}
                onChange={(value) => {
                  if (value === "" || /^\d+$/.test(value)) {
                    setExpiryHours(value);
                  }
                }}
              />
            </Grid.Cell>
          </Grid>

          <Grid>
            {/* Flags */}
            <Grid.Cell size={Grid.CellSize.S3}>
              <Checkbox
                label="One-Time Scan"
                isChecked={isOneTimeScan}
                isDisabled={isLoading || isSuccess}
                onChange={setIsOneTimeScan}
              />
            </Grid.Cell>

            <Grid.Cell size={Grid.CellSize.S3}>
              <Checkbox
                label="Gate Validation Required"
                isChecked={isGateValidation}
                isDisabled={isLoading || isSuccess}
                onChange={setIsGateValidation}
              />
            </Grid.Cell>

            <Grid.Cell size={Grid.CellSize.S3}>
              <Checkbox
                label="PDF Generation Required"
                isChecked={isPdfRequired}
                isDisabled={isLoading || isSuccess}
                onChange={setIsPdfRequired}
              />
            </Grid.Cell>

            <Grid.Cell size={Grid.CellSize.S3}>
              <Checkbox
                label="Active"
                isChecked={isActive}
                isDisabled={isLoading || isSuccess}
                onChange={setIsActive}
              />
            </Grid.Cell>
          </Grid>
        </Paper>
      </Dashboard.Page>
    </Dashboard.Content>
  );
};